name: Update and publish wiki
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository itself
        uses: actions/checkout@v2
      - name: Checkout repository wiki
        uses: actions/checkout@v2
        with:
          repository: zietzm/phenotype_standardization.wiki
          path: phenotype_standardization.wiki
      - name: Build wiki page
        run: |
          mkdir wiki/outputs/
          python3 wiki/build_wiki.py
      - name: Push updated wiki
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          mv wiki/outputs/*.md phenotype_standardization.wiki/
          cd phenotype_standardization.wiki/
          WIKI_REPO_URL="https://${GH_PERSONAL_ACCESS_TOKEN}@github.com/zietzm/phenotype_standardization.wiki.git"
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Automatically publish wiki";
            git push --set-upstream "$WIKI_REPO_URL" master;
          else
            echo "No changes";
          fi
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
